USE FinansijskiSistem;
GO

CREATE ROLE DbDeveloper;
GO

CREATE ROLE DbApiDeveloper;
GO

CREATE USER Jova WITHOUT LOGIN;
GO

CREATE USER Mila WITHOUT LOGIN;
GO

ALTER ROLE DbDeveloper ADD MEMBER Jova;
GO

ALTER ROLE DbApiDeveloper ADD MEMBER Mila;
GO

CREATE APPLICATION ROLE DataProviderFINANSIJE
WITH PASSWORD = 'Fin@nsije2025!',
DEFAULT_SCHEMA = api_finansije;
GO

CREATE APPLICATION ROLE DataProviderKONTROLA
WITH PASSWORD = 'K0ntr0la2025!',
DEFAULT_SCHEMA = api_kontrola;
GO

GRANT ALTER, EXECUTE, SELECT, INSERT, UPDATE, DELETE ON SCHEMA::impl TO DbDeveloper;
GO

GRANT ALTER, EXECUTE, SELECT, INSERT, UPDATE, DELETE ON SCHEMA::spec TO DbDeveloper;
GO

GRANT ALTER, EXECUTE, SELECT, INSERT, UPDATE, DELETE ON SCHEMA::api_finansije TO DbApiDeveloper;
GO

GRANT ALTER, EXECUTE, SELECT, INSERT, UPDATE, DELETE ON SCHEMA::api_kontrola TO DbApiDeveloper;
GO

GRANT EXECUTE, SELECT ON SCHEMA::api_finansije TO DataProviderFINANSIJE;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::impl TO DataProviderFINANSIJE;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::spec TO DataProviderFINANSIJE;
GO

GRANT SELECT ON SCHEMA::api_kontrola TO DataProviderKONTROLA;
GO

GRANT EXECUTE ON OBJECT::api_kontrola.KumulativniIzvestaj TO DataProviderKONTROLA;
GO

GRANT EXECUTE ON OBJECT::api_kontrola.PretragaTransakcija TO DataProviderKONTROLA;
GO

GRANT EXECUTE ON OBJECT::api_kontrola.AktivniUpiti TO DataProviderKONTROLA;
GO

DENY INSERT, UPDATE, DELETE ON SCHEMA::api_kontrola TO DataProviderKONTROLA;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::impl TO DataProviderKONTROLA;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::spec TO DataProviderKONTROLA;
GO
